### ISSUE TITLE
No SeasonTeamHistory error when importing playoff data

### ISSUE THREAD

**Issue by DantheChef** [tbrittain/SmbExplorerCompanion#111]
On version 1.0.1, importing regular season data works fine, importing playoff data just throws an error saying that No SeasonTeamHistory record was found. Every time I relaunch and try to import the playoff data, it shows a different team ID. I attached the CSVs.

![image](https://github.com/tbrittain/SmbExplorerCompanion/assets/26890375/4b0d25cc-0410-4f16-83d8-9be49b4452ff)
![image](https://github.com/tbrittain/SmbExplorerCompanion/assets/26890375/6a876779-fcf0-4bc5-b666-b4bd5961cc3e)
[SMB4S1.zip](https://github.com/tbrittain/SmbExplorerCompanion/files/12876470/SMB4S1.zip)

**Comment by tbrittain** [comment]
Thanks for attaching the CSVs. I'll look into this ASAP

**Comment by tbrittain** [comment]
I may have found the source of this bug. Looks like there were some checks in assigning the order of a player to teams that they were a part of during the previous season that did not account for a specific case where the "Current Team" and the "Most Recent Team" were different (as they are identical >99% of the time, and in fact somehow I never encountered this personally, after dozens of seasons of imports), so I am going to make sure this is accounted for. When it came to the playoff data throwing the exception, it was looking for the team ID matching the "Current Team", which didn't exist in the proper state from the regular season import.

I plan on making a hotfix release for this sometime tomorrow. This will require a re-import of your first season data. If that doesn't fix the issue, then we may need to wipe the slate clean and try from a fresh database, but hopefully it doesn't come to that!

**Comment by tbrittain** [comment]
I will be testing this tomorrow and will update when a fix is ready

**Comment by tbrittain** [comment]
Just completed the fix. Tested with your regular season and playoff data and it imported successfully. Will be creating a build for this soon. It is a hotfix, but I'll probably bump the minor version since it's a critical fix and I want all downloaded clients to be notified to update
