### ISSUE TITLE
Season awards screen crash and unintended text box

### ISSUE THREAD

**Issue by DantheChef** [tbrittain/SmbExplorerCompanion#131]
This is on Version 1.2.1
On the season awards screen, you can click on the players name and it's actually a text box, if you change the name and then press enter, it will crash a few seconds later.
https://github.com/tbrittain/SmbExplorerCompanion/assets/26890375/ab67bdb2-b0a9-4e97-9586-b97541fdb30d

**Comment by tbrittain** [comment]
Thanks for the video, this is very helpful. I haven't checked why exactly this is occurring, but I thought I disabled interaction with all grid columns that aren't supposed to be edited. Looks like that may have not been the case for the grids on that page, so I'll work on this asap
