### ISSUE TITLE
Update names when importing

### ISSUE THREAD

**Issue by DantheChef** [tbrittain/SmbExplorerCompanion#164]
If you change the name of a player you've previously imported, the former name is the one that is shown. It would be great if the name was updated and changed, with maybe the previous name being shown too.

**Comment by tbrittain** [comment]
@DantheChef fixed as of the most recent release! (1.2.7)

**Comment by DantheChef** [comment]
> @DantheChef fixed as of the most recent release! (1.2.7)

Thank you so much!

**Comment by tbrittain** [comment]
You're welcome!!
