### ISSUE TITLE
Header with name X not found 

### ISSUE THREAD

**Issue by NathannW94** [tbrittain/SmbExplorerCompanion#206]
**Describe the bug**
When Importing the CSV files from SMB Explorer, I’m getting an error detailing that it’s failing to find certain headers. See pic attached. 

This is using exports for the regular season, exported at the end of all reg season games before moving to the playoffs. 

The error reads: 

header with name X was not found: 
TeamID 
Runs for 
Runs against 
Pythagorean WPTC 
Expected W 
Expected L 

![065D9969-496D-48AF-8E7D-FC1B0FECC837](https://github.com/user-attachments/assets/61d14608-40fb-45dd-933e-b6980cd714db)

**Comment by tbrittain** [comment]
Hey thank you for the bug report! Can you send the CSV that you are trying to import? And also what version of SMB Explorer + the Companion app? And just to make sure - you didn't rename any of the column headers that were originally exported?

**Comment by NathannW94** [comment]
hi Trey,

thanks for getting back to me!

attached are the CSVs.

companion is 1.3.0, explorer 1.5.0

no headers have been renamed.

cheers, nathan
________________________________

**Comment by NathannW94** [comment]
Trey I’ve just realised I’ve been exporting with an old version of the explorer.

Must have used an old link from Reddit.

I’ll try that and report back

Nathan

From: Nathan Wrigglesworth ***@***.***>
Date: Wednesday, 21 August 2024 at 20:02
To: tbrittain/SmbExplorerCompanion ***@***.***>
Subject: Re: [tbrittain/SmbExplorerCompanion] Header with name X not found (Issue #206)

hi Trey,

thanks for getting back to me!

attached are the CSVs.

companion is 1.3.0, explorer 1.5.0

no headers have been renamed.

cheers, nathan
________________________________

**Comment by tbrittain** [comment]
Hi Nathan, sounds good! Let me know if that fixes the issue, otherwise I can certainly look into it!

**Comment by NathannW94** [comment]
Hi Trey,

As expected it was human error. The latest versions of the apps work perfectly. You can remove/resolve that bug report.

Amazing little app btw! Obsessed. My Steam Deck has become a portable baseball world.

Cheers,

Nathan

From: Trey Brittain ***@***.***>
Date: Wednesday, 28 August 2024 at 17:54
To: tbrittain/SmbExplorerCompanion ***@***.***>
Cc: NathannW94 ***@***.***>, Author ***@***.***>
Subject: Re: [tbrittain/SmbExplorerCompanion] Header with name X not found (Issue #206)


Hi Nathan, sounds good! Let me know if that fixes the issue, otherwise I can certainly look into it!

**Comment by tbrittain** [comment]
Awesome, happy to hear it! Closing this out now, appreciate it!
